Portfolio Project - Projects Details Popup
mwismann/mwismann.github.io pull request #6
Opened 2023-01-31 21:09 UTC by mwismann

### Portfolio Project - Projects Details Popup 😎 
**In this feature branch, my coding partners and I worked on the following features:**

- Created a function that allows the popup with details about the project to appear when the user clicks (or taps) the button to check project details,  ✅ 
- Created a function that makes the popup disappear when the user clicks (or taps) the close (X) button,  ✅ 
- Stored all the necessary information for the projects inside of Objects ✅
-  Stored all the Objects in an Array ✅

2023-01-31 22:40 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-31 22:40 UTC, Qoosim commented on styles.css
> +}
- [ ] It is required to stick to the template design as much as possible. Your pop up box is not properly positioned to the center of the page as we have it on the guiding template you chose. Kindly look at the both designs and work your design alongside the Figma template you chose. This applies to both the desktop and mobile versions.

### Your Desing Desktop
![desktop](https://user-images.githubusercontent.com/26597432/215896762-3f59d26e-e160-42b1-b616-63bbd9b32f3f.png)

### Figma Design Desktop
![temp-desktop](https://user-images.githubusercontent.com/26597432/215896799-29684a96-4709-4ba0-957a-d4ecb4b88f40.png)


### Your Design Mobile
![mobile](https://user-images.githubusercontent.com/26597432/215896837-68123b74-f6cd-4679-ace9-a3440fccbdb1.png)

### Figma Design Mobile
![temp-mobile](https://user-images.githubusercontent.com/26597432/215896879-60a5b756-b5ce-46e9-afaf-8e34e69725fe.png)

2023-01-31 22:40 UTC, Qoosim commented on index.html
>                  <div class="works-grid-card">
- [ ] It is required that the projects section is created dynamically with the information from the projects array (all the HTML of the section is created when the page loads). This requires changes in existing code - already created HTML code for projects list should be removed, and instead it should be added via JavaScript. This is contained in the project requirements. Kindly take a look at the project requirements once again, remove already created html codes for the project sections and create them dynamically from your js file.

![project-rqts](https://user-images.githubusercontent.com/26597432/215899479-bd7bcf80-7182-4a86-9346-149b78a30d24.png)

2023-02-01 18:08 UTC, BregornOriginal approved these changes
## Hi @mwismann  

## Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! :gorro_de_fiesta:

![allfather-approves-approved](https://user-images.githubusercontent.com/93630700/216125386-1325562e-4726-46fe-94a1-be71c683199c.gif)

## Highlights

✅ Linters are passing
✅ Good commit history

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

2023-02-01 18:41 UTC, merged